spring:
  rabbitmq:
    host: 133.186.228.84
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://133.186.244.96:3306/nhn_academy_14
    username: nhn_academy_14
    password: wvSjRM8JGjjK]ZnJ
    driver-class-name: com.mysql.cj.jdbc.Driver

rabbitmq:
  queue:
    name: mqtt-subscription-CENSYSqos0

  exchange:
    name: sample-exchange
  routing:
    key: key

