spring:
  rabbitmq:
    host: 103.218.158.101
    port: 5672
    name: databo3-prod
    username: guest
    password: guest
  influxdb2:
    url: http://180.210.83.241:8086
    bucket: raw_data
    token: 5EI2DnDnlObO01V2sZPwEWBujxz13V5ZainoRp-XUcVocBqMBfxoa-R6Ok0g1NTSSH6wtVoQX3WsmPWSHNniLg==
    org: databo3

predict:
  api:
    url: http://125.6.36.234:5000