spring:
  rabbitmq:
    host: 133.186.228.84
    port: 5672
  influxdb2:
    url: http://133.186.251.19:8086
    bucket: databo3
    token: _gmvJCS_Q-zVy9V1VJ3CDkO5NA963NYfq9EIniHJqpktedhGH_lNBekFS96ds0L0bMrOybrkuLhlX4xLCDf8Pg==
    org: databo3

rabbit:
  queue:
    name: test-queue

node-flow:
  setting:
    -
      node-name: 'rabbit-node-1'
      node-type: 'RabbitMQ-in'
      environment-name: 'rabbit-env-1'

    -
      node-name: 'influx-node-1'
      node-type: 'InfluxDB-out'
      environment-name: 'influx-env-1'


  environments:
    rabbitMQ-environment:
      environmentName: 'rabbit-env-1'
      rabbitHost: '133.186.228.84'
      rabbitPort: 5672
      rabbitQueue: 'test-queue'

    influxDB-environment:
      environmentName: 'influx-env-1'
      influxUrl: 'http://133.186.251.19:8086'
      influxBucket: 'databo3'
      influxOrg: 'databo3'
      influxToken: '_gmvJCS_Q-zVy9V1VJ3CDkO5NA963NYfq9EIniHJqpktedhGH_lNBekFS96ds0L0bMrOybrkuLhlX4xLCDf8Pg=='
