spring:
  rabbitmq:
    host: 133.186.228.84
    port: 5672
    name: test-queue
  influxdb2:
    url: http://133.186.251.19:8086
    bucket: databo3
    token: _gmvJCS_Q-zVy9V1VJ3CDkO5NA963NYfq9EIniHJqpktedhGH_lNBekFS96ds0L0bMrOybrkuLhlX4xLCDf8Pg==
    org: databo3

rabbit:
  queue:
    name: test-queue

