spring:
  rabbitmq:
    host: 133.186.228.84
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: test-queue
  exchange:
    name: sample-exchange
  routing:
    key: key